services:
  db:
    image: postgres
    container_name: postgres-ud-vote
    ports:
      - "5454:5432"
    environment:
      - POSTGRES_DB=app-db-name
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
    volumes:
      - ./postgres-ud-vote:/var/lib/postgresql/data
    restart: always

  ud-vote:
    build: .
    container_name: ud-vote
    image: app/ud-vote:latest
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - db
    command: ["./wait-for-it.sh", "db:5432", "--", "java", "-jar", "ud_vote.jar"]
    restart: always

