spring:
  application:
    name: ud-vote-spring

  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 30
        order_updates: true
    show-sql: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  error:
    include-message: always

jwt:
  secret: ${JWT_SECRET}

admin:
  default:
    username: ${ADMIN_DEFAULT_USERNAME}
    password: ${ADMIN_DEFAULT_PASSWORD}
    email: ${ADMIN_DEFAULT_EMAIL}

logging:
  level:
    root: INFO
    com:
      goodamcodes: DEBUG

url:
  image: uploads/images/
  video: uploads/videos/
  document: uploads/files/
