name: Build & Push UDVote Docker Image

on:
  push:
    branches:
      - main

jobs:

  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/ud-vote:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/ud-vote:latest
          cache-to: type=inline
